title: Currículo Marcelo Barbosa
email: marcelo.bar.eng@gmail.com
description: >-
  Currículo online com projetos, experiências e sistemas desenvolvidos por Marcelo Barbosa.
baseurl: "/curriculo-online" # subcaminho do repositório, muito importante!
url: "https://marcelo0070.github.io" # domínio principal do GitHub Pages

twitter_username: ""
github_username: marcelo0070

theme: minima

plugins:
  - jekyll-feed

# Adicione esta parte se você quiser que essas pastas sejam ignoradas
exclude:
  - node_modules/
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - vendor/
